version: "3"

services:
  web:
    build:
      context: .
      dockerfile: DockerfilePro
    container_name: dg01
    command: >
      bash -c "python manage.py collectstatic --no-input &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/app
      - static_volume:/app/static
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings.product

  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network: