# Generated by Django 5.1 on 2024-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="다람쥐8CxUi", max_length=255, unique=True, verbose_name="닉네임"),
        ),
    ]
