# Generated by Django 5.1 on 2024-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="판다mxdp4", max_length=255, unique=True, verbose_name="닉네임"),
        ),
    ]
