# Generated by Django 5.1 on 2024-08-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="크림치즈병아리aGZ1J", max_length=255, unique=True, verbose_name="닉네임"),
        ),
    ]
