name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose-pro.yml build web
          docker-compose -f docker-compose-pro.yml push web

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            git stash
            git switch develop
            git pull origin develop
            cd /home/ec2-user/oz_03_collabo-001-BE/django

            sudo find . -path "*/migrations/*.py" -not -name "__init__.py" -exec rm {} \;
            sudo find . -path "*/migrations/*.pyc" -exec rm {} \;

            cd /home/ec2-user/oz_03_collabo-001-BE 
            sudo docker-compose -f docker-compose.yml up --build -d

