name: Python Formatter (isort & black)

on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check-only .